### ISSUE TITLE
request for more informaion

### ISSUE THREAD

**Issue by yuchi81** [krikjers/Master_thesis#1]
Could you give more information about the related thesis, such as your  master's thesis, SBMPC algorithm by Johansen, PhD thesis by Woerner (2016)? Thank you very much.

**Comment by krikjers** [comment]
Hi! You can find the thesis here

https://ntnuopen.ntnu.no/ntnu-xmlui/handle/11250/2780862

here, the work by woerner and johansen is also described

**Comment by yuchi81** [comment]
Thank you very much for your generous help and prompt reply.
